<<<<<<< HEAD
SRC_SV := src/lsu_stb_controller.sv        \
          src/stb_cache_controller.sv      \
          src/store_buffer_top.sv          \
          src/store_buffer_datapath.sv              \
          test/tb_store_buffer_top.sv
=======
SRC_SV:= src/lsu_stb_controller.sv		\
	src/stb_cache_controller.sv 		\
	src/store_buffer_top.sv				\
	src/store_buffer_datapath.sv		\
	test/tb_store_buffer_top.sv
	
DEFS:= defines/*.svh
>>>>>>> c57e843 (docs and src are updated)

DEFINES_VER := src/defines/verilator.svh

COMP_OPTS_SV := --incr --relax

TB_TOP := tb_store_buffer_top
MODULE := tb_store_buffer_top

WORK_DIR = work

#==== Default target - running VIVADO simulation without drawing waveforms ====#
.PHONY: vivado viv_elaborate viv_compile

vivado : $(TB_TOP)_snapshot.wdb

viv_elaborate : .elab.timestamp

viv_compile : .comp_sv.timestamp .comp_v.timestamp .comp_vhdl.timestamp

#==== WAVEFORM DRAWING ====#
.PHONY: viv_waves
viv_waves : $(TB_TOP)_snapshot.wdb
	@echo
	@echo "### OPENING VIVADO WAVES ###"
	xsim --gui $(TB_TOP)_snapshot.wdb

#==== SIMULATION ====#
$(TB_TOP)_snapshot.wdb : .elab.timestamp 
	@echo
	@echo "### RUNNING SIMULATION ###"
	xsim $(TB_TOP)_snapshot --tclbatch xsim_cfg.tcl

#==== ELABORATION ====#
.elab.timestamp : .comp_sv.timestamp .comp_v.timestamp .comp_vhdl.timestamp
	@echo 
	@echo "### ELABORATION ###"
	xelab -debug all -top $(TB_TOP) -snapshot $(TB_TOP)_snapshot
	touch $@	

#==== COMPILING SYSTEMVERILOG ====#	
ifeq ($(SRC_SV),)
.comp_sv.timestamp :
	@echo 
	@echo "### NO SYSTEMVERILOG SOURCES GIVEN ###"
	@echo "### SKIPPED SYSTEMVERILOG COMPILATION ###"
	touch $@
else 
.comp_sv.timestamp : $(SRC_SV)
	@echo
	@echo "### COMPILING SYSTEMVERILOG ###"
	rm -rf xsim_cfg.tcl
	@echo "log_wave -recursive *" > xsim_cfg.tcl
	@echo "run all" >> xsim_cfg.tcl
	@echo "exit" >> xsim_cfg.tcl
	#verilog -VIVADO  
	xvlog -sv $(COMP_OPTS_SV) $(SRC_SV) #$(DEFINES_VIV)
	touch $@
endif

#==== COMPILING VERILOG ====#	
ifeq ($(SRC_V),)
.comp_v.timestamp :
	@echo
	@echo "### NO VERILOG SOURCES GIVEN ###"
	@echo "### SKIPPED VERILOG COMPILATION ###"
	touch $@
else
.comp_v.timestamp : $(SRC_V)
	@echo 
	@echo "### COMPILING VERILOG ###"
	xvlog $(COMP_OPTS_V) $(SRC_V)
	touch $@
endif 

#==== COMPILING VHDL ====#	
ifeq ($(SRC_VHDL),)
.comp_vhdl.timestamp :
	@echo
	@echo "### NO VHDL SOURCES GIVEN ###"
	@echo "### SKIPPED VHDL COMPILATION ###"
	touch $@
else
.comp_vhdl.timestamp : $(SRC_VHDL)
	@echo 
	@echo "### COMPILING VHDL ###"
	xvhdl $(COMP_OPTS) $(SRC_VHDL)
	touch $@
endif
	
#----------------------#
#----- MODEL SIM ------#
#----------------------#

vsim: vsim_compile simulate

# Create a working library and compile source files
vsim_compile: $(wildcard *.sv)
	@echo "Creating work library..."
	vlib $(WORK_DIR)
	@echo "Compiling source files..."
	vlog -work $(WORK_DIR) $(SRC_SV) $(DEFS)

# Run the simulation and generate WLF file
simulate: vsim_compile
	@echo "Running simulation..."
	vsim -L $(WORK_DIR) $(MODULE) -do "add wave -radix Unsigned sim:/$(MODULE)/DUT/*; run -all"

#----------------------#
#----- ICARUS VERILOG --#
#----------------------#

# Compile and simulate using Icarus Verilog
.PHONY: iverilog
iverilog: $(SRC_SV)
	@echo
	@echo "### COMPILING WITH ICARUS VERILOG ###"
	iverilog -g2012 -o $(TB_TOP).vvp $(SRC_SV)

# Run the simulation using Icarus Verilog and generate a VCD waveform file
.PHONY: vvp
vvp: iverilog
	@echo
	@echo "### RUNNING SIMULATION WITH VVP ###"
	vvp $(TB_TOP).vvp

# View the waveform generated by Icarus Verilog
.PHONY: view_wave
view_wave: vvp
	@echo
	@echo "### VIEWING WAVEFORM WITH GTKWave ###"
	gtkwave dump.vcd &

# Clean up all generated files
.PHONY : clean
clean :
	@echo "Cleaning up..."
	rm -rf $(WORK_DIR) transcript vsim.wlf
	rm -rf *.jou *.log *.pb *.wdb xsim.dir *.str
	rm -rf .*.timestamp *.tcl *.vcd .*.verilate
	rm -rf obj_dir .Xil $(TB_TOP).vvp